#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

message="$(cat "$1")"
requiredPattern='^[A-Za-z]+-[0-9]+: .+$'

if ! echo "$message" | grep -qE "$requiredPattern"; then
  echo "-"
  echo "🚨 Wrong commit message! 😕"
  echo "The commit message must have this format:"
  echo "<JIRA_ISSUE_KEY>: <PR title plus other description, if required>"
  echo "':' - is required after the JIRA issue number"
  echo "Example:"
  echo "ABC-123: Add login button"
  echo "-"
  echo "Your commit message was:"
  echo "$message"
  echo "-"
  echo "For more information, check script in .husky/commit-msg"
  echo "-"
  exit 1
fi
