name: Code quality check

on:
  push:
    branches: [ master, eca_trunk ]
  pull_request:
    branches: [ master, eca_trunk ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.12.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check
        run: |
          yarn install
#          yarn lint-check
